services:
  - type: web
    name: task-management-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn BaseApp.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: BaseApp.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
